local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

azure:
  service: AzureStorage
  storage_account_name: <%= ENV['STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  container: <%= ENV['STORAGE_CONTAINER'] %>